Consider keyword arguments in the interactor.
hanami/utils pull request #379
Opened 2020-08-31 03:23 UTC by ippachi

```
require 'hanami/interactor'

class A
  include Hanami::Interactor
  def call(test, a:, b:)
    puts test, a, b
  end
end

A.new.call({ test: 1 }, a: 2, b: 3)
```

This code output warning about the keyword argument of ruby 2.7.
So I declared the keyword argument explicitly.

2020-12-04 08:28 UTC, jodosha requested changes
@ippachi Thanks for this PR, but..

It doesn't fix all the warnings:

```
/Users/luca/Code/hanami/utils/spec/unit/hanami/interactor_spec.rb:522: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/luca/Code/hanami/utils/lib/hanami/interactor.rb:354: warning: The called method `call' is defined here
F/Users/luca/Code/hanami/utils/spec/unit/hanami/interactor_spec.rb:295: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/luca/Code/hanami/utils/spec/unit/hanami/interactor_spec.rb:318: warning: The called method `build_user' is defined here
```

...and it causes a spec failure:

```

Failures:

  1) Hanami::Interactor new interface #call handles args with to_hash method
     Failure/Error: expect(result.args).to eql(Array[user])

       expected: [#<User:0x00007f965d27c950 @attributes={:name=>"Luca"}>]
            got: [{:name=>"Luca"}]

       (compared using eql?)

       Diff:
       @@ -1 +1 @@
       -[#<User:0x00007f965d27c950 @attributes={:name=>"Luca"}>]
       +[{:name=>"Luca"}]

     # ./spec/unit/hanami/interactor_spec.rb:523:in `block (4 levels) in <top (required)>'
```

Please consider to rebase with `master` and then fix the code. Thanks. 😃

2020-12-07 02:21 UTC, ippachi commented
Sorry incompleted PR.
I'll fix it! 😄

2020-12-27 11:22 UTC, ippachi commented
I fixed.
This is not clean code so I think there is better way.
But I have no idea. 😢 

@jodosha

2021-02-19 15:08 UTC, jodosha requested changes
@ippachi This is a hacky solution. 😞

2021-02-19 15:09 UTC, jodosha commented
With v1.3.7 and the upcoming v1.3.8 we'll have this to work well with both args and kwargs with Ruby 2.7 and 3.0.

2021-02-19 15:09 UTC, closed without merging